---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: seafoam
# description will be included in the image's metadata
description: An experimental atomic Linux distro.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      - mkdir /var/nix /nix
      - echo "/var/nix /nix none bind,nobootwait 0 0" >> /etc/fstab
      - curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - firefox

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
