---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: seafoam
# description will be included in the image's metadata
description: An experimental atomic Linux distro.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - from-file: system-files.yml
  - from-file: config/change-os-release.yml
  - from-file: config/default-flatpaks.yml
  - from-file: config/dnf-packages.yml
  - from-file: config/chezmoi-setup.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
